# Generated by Django 4.2.10 on 2024-02-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="is_int",
            field=models.IntegerField(default=1),
        ),
    ]
