# Generated by Django 4.2.10 on 2024-02-26 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_rename_is_int_question_survey_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_name", models.CharField(default="text", max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="question",
            name="survey_type",
        ),
        migrations.AddField(
            model_name="question",
            name="surveytype",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.surveytype",
            ),
        ),
    ]
