# Generated by Django 4.2.10 on 2024-02-26 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_surveytype_remove_question_survey_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='int_value',
        ),
    ]
