# Generated by Django 4.2.10 on 2024-05-04 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_question_value_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="survey_ETAmin",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="survey",
            name="survey_img",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="survey",
            name="survey_index_description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="survey",
            name="survey_subtitle",
            field=models.CharField(default="", max_length=300),
        ),
        migrations.AddField(
            model_name="survey",
            name="survey_title",
            field=models.CharField(default="", max_length=300),
        ),
        migrations.CreateModel(
            name="CompletedSurvey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.survey"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.user"
                    ),
                ),
            ],
            options={
                "db_table": "completed_survey",
            },
        ),
    ]
