# Generated by Django 4.2.10 on 2024-05-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_question_value_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_details',
            new_name='question_details_en',
        ),
        migrations.AddField(
            model_name='question',
            name='question_class',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='question',
            name='question_details_ko',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='question_index',
            field=models.IntegerField(default=-1),
        ),
    ]
