# Generated by Django 4.2.10 on 2024-05-02 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_question_details_question_question_details_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_class',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_details_ko',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_index',
        ),
    ]
