# Generated by Django 4.2.10 on 2024-05-04 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_survey_survey_etamin_survey_survey_img_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="question_basic",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="question",
            name="question_subtitle",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="question",
            name="question_title",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_details",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="survey",
            name="survey_subtitle",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="survey",
            name="survey_title",
            field=models.TextField(default=""),
        ),
    ]
