# Generated by Django 4.2.10 on 2024-05-02 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_question_question_class_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_details_en',
            new_name='question_details',
        ),
    ]
