# Generated by Django 4.2.10 on 2024-05-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_question_question_basic_question_question_subtitle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="question_required",
            field=models.BooleanField(default=True),
        ),
    ]
