# Generated by Django 4.2.10 on 2024-05-04 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_question_question_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="survey_number",
            field=models.IntegerField(default=-1),
        ),
    ]
