# Generated by Django 4.2.10 on 2024-05-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_survey_survey_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="question_label",
            field=models.CharField(default="emotion", max_length=200),
        ),
    ]
