# Generated by Django 4.2.10 on 2024-05-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_survey_survey_notice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="survey",
            name="survey_notice",
        ),
        migrations.AddField(
            model_name="question",
            name="question_notice",
            field=models.TextField(default=""),
        ),
    ]
