# Generated by Django 4.2.10 on 2024-05-07 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_rename_question_details_en_question_question_details"),
        ("app", "0016_remove_survey_survey_notice_question_question_notice"),
    ]

    operations = []
