# Generated by Django 4.2.10 on 2024-05-08 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adminid", models.CharField(max_length=200)),
                ("password", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "admin",
            },
        ),
    ]
